name: âš™ï¸ Check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  setup:
    name: ðŸ—ï¸ Setup Environment
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # or your locked version
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node_modules and pnpm store
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Persist node_modules and pnpm store
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node_modules_and_store
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
  format:
    name: ðŸ§± Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Prettier - Format
        run: pnpm format

  lint:
    name: ðŸ”Ž Eslint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Eslint
        run: pnpm lint

  build:
    name: ðŸ›« Build Library
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build library
        run: pnpm build

  vitest:
    name: ðŸ§ª Vitest
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Vitest - Library
        run: pnpm test
