name: ‚öôÔ∏è Check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  setup:
    name: üèóÔ∏è Setup Environment
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node_modules and pnpm store
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Persist node_modules and pnpm store
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node_modules_and_store
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.pnpm_store_path }}

  format:
    name: üß± Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download cached node_modules and pnpm store
        uses: actions/download-artifact@v4
        with:
          name: node_modules_and_store

  build:
    name: üèóÔ∏è Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download cached node_modules and pnpm store
        uses: actions/download-artifact@v4
        with:
          name: node_modules_and_store

  test:
    name: üß™ Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download cached node_modules and pnpm store
        uses: actions/download-artifact@v4
        with:
          name: node_modules_and_store

  lint:
    name: üïµÔ∏è Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download cached node_modules and pnpm store
        uses: actions/download-artifact@v4
        with:
          name: node_modules_and_store
